### ISSUE TITLE
[SP3] Research which kinds of SSEVP Waves we'd be looking at

### ISSUE THREAD

**Issue by priyanshumahey** [UBCMint/NTX-2022-Project#3]
# Research SSEVP Waves
## Overview
For our project, we'd be looking into SSEVP at one point so we need to analyze exactly what SSEVP waves would look like and when they would occur.

## Timeline
We want this task to be done by roughly next week as we want to know as soon as possible what kinds of SSEVP waves we should anticipate and what they should look like. 

## Technical Overview
This is a mainly about conducting some research on past literature and seeing how SSEVP brain waves are generated. We need to ensure that we know what SSEVP brain waves look like, how they're generated, when they occur and why the occur. 

## Submission Guidelines 
You'll be submitting this as a google doc on the MINT google drive under signal processing. Then link the doc here in the comments.

## Comments and Questions
For any questions, feel free to message @priyanshumahey.

**Comment by faranehym** [comment]
https://docs.google.com/document/d/131R8vIjLegR7t5Z8p66n4yJ3nOdLSh42c-1oymKLLTo/edit
