### ISSUE TITLE
[SP6] Look Deeper into Size Brainwaves

### ISSUE THREAD

**Issue by priyanshumahey** [UBCMint/NTX-2022-Project#6]
# Look Deeper into Size Brainwaves
## Overview
You'll need to do research into size specific EEG and figure out how exactly size changes could be detected through EEG. Size changing EEG is probably the more difficult one. If you can't find anything for this, we could also do focus and no focus for size changes.

## Timeline
We ideally want this done by next week to have enough time to gather EEG data 

## Technical Overview
You'll need to read papers to see how they've done size change detection and see their methods of implementation. The main focus is seeing stimulus required and the brainwaves that come up as a result of the exposing people to shapes changing sizes.

## Submission Guidelines 
Add it to the MINT google drive in a google doc.

## Comments and Questions
For any questions, message @priyanshumahey

**Comment by faitht1023** [comment]
-Closing/opening your eyes to make the cube bigger
-Consider 5s eyes closed, 10s eyes open
